name: Update Submodule

on:
  push:
    branches:
      - main

jobs:
  update_submodule:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Update Submodule
        run: |
          git submodule update --remote --recursive
          git add odoo_custom_projects
          git config --global user.name 'Sanjana-ks'
          git config --global user.email 'sanjana.gharewal@ksolves.com'
          git commit -m "Update main repository submodule"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
